### ISSUE TITLE
I don't quite understand. 

### ISSUE THREAD

**Issue by LiangCha01** [za233/Polaris-Obfuscator#2]
I don't quite understand. How to build it, I have the source code in the warehouse now, and then downloaded the official 16.0.6 source code, and found that it was exactly the same and no changes were found.

**Comment by za233** [comment]
please check out the folder: src/llvm/lib/Transforms/Obfuscation, you will see the obfuscation passes' source code.

**Comment by LiangCha01** [comment]
Hello, I downloaded the source code from your warehouse and then downloaded the file from the following link.
https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.6/llvm-16.0.6.src.tar.xz
I compared the files in the Obfuscation folder you mentioned below and found that they are the same.

**Comment by za233** [comment]
obviously, you have already copied it into the project's folder.

**Comment by LiangCha01** [comment]
I actually don't understand this passage
Download the complete LLVM-16.0.6 project and copy the llvm folder from src into the LLVM project directory.

**Comment by za233** [comment]
you need to copy the llvm folder from the src folder in this repository to the llvm project's folder. it is a patch, so file replacement will happen. then build the llvm-project

**Comment by LiangCha01** [comment]
I understand, there is no path src/llvm/lib/Transforms/Obfuscation in the original version. The first time I tried to copy it, I found that the files were the same, and then I stopped copying. I re-decompressed the source code and found the difference.

**Comment by LiangCha01** [comment]
Can I directly copy src/llvm/lib/Transforms/Obfuscation to the complete project? Or do I need to copy them all to the complete project?

**Comment by za233** [comment]
you need copy them all, because the implementation of backend obfuscation is based on modifying llvm backend's code.

**Comment by LiangCha01** [comment]
Well, because copying takes 2 hours

**Comment by LiangCha01** [comment]
I thought I could copy the specified folder directly

**Comment by za233** [comment]
afterwards, I can try reducing the size of the LLVM source code included.

**Comment by LiangCha01** [comment]
其实可以直接把复制的源代码打包起来，这样大家就不用复制一次了，因为有6万多个文件，所以很费时间。

**Comment by LiangCha01** [comment]
In fact, you can directly package the copied source code, so that everyone does not need to copy it once, which is very time-consuming because there are more than 60,000 files.

**Comment by za233** [comment]
thank you for the reminder. i am currently doing so

**Comment by LiangCha01** [comment]
There is another problem. When I copied, a pop-up window appeared to ask whether to replace. I chose to replace.

**Comment by LiangCha01** [comment]
I would like to ask if llvm-16.0.6 can be used under vs2019?

**Comment by za233** [comment]
of course.

**Comment by LiangCha01** [comment]
It took you some time, thank you for your patience in answering.
