### ISSUE TITLE
There is another question

### ISSUE THREAD

**Issue by LiangCha01** [za233/Polaris-Obfuscator#3]
I don’t know if it’s a feature of clang or something else. After I used llvm 17.0.6 to compile the program on 2022, a simple "Hello Wordrd" will also cause static scanning by anti-virus software. No matter what is compiled, it will be considered a virus. I suspect it is a problem with the llvm version, so I want to use your modified version to try on vs2019 to see if it is considered a virus. Can the author modify the characteristics of clang? Do you think it’s a compilation version problem?

**Comment by za233** [comment]
I think this may be a misjudgment by antivirus software. The program compiled by clang should not be marked, at least I haven't encountered this situation before.

**Comment by LiangCha01** [comment]
360 Security Guard is like this

**Comment by LiangCha01** [comment]
It must be misjudgment, but I don't know how to solve the false positive, so I want to try your modified version to see if this happens.

**Comment by za233** [comment]
Perhaps this is a problem with 360 Security Guard. You can try uploading your program to Virus Total and see the result.

**Comment by LiangCha01** [comment]
Virus Total checks dynamically, and there should be no static detection.

**Comment by za233** [comment]
I think this may be caused by some linked library functions. You can try using this version, but there is a high possibility that it won't work because it will only obfuscate the code you write.

**Comment by LiangCha01** [comment]
When I use the vs2019 tool set to compile, there will be no false positives. When the compiler is selected as clang, the compiled program is in a virus reporting state. This should mean that 360 Security Guard has pulled the clang feature into the black platform.

**Comment by za233** [comment]
It's hard to imagine that an antivirus software could do such a thing.

**Comment by LiangCha01** [comment]
As far as I know, this 360 Security Guard uses a black and white list mechanism. If you want to add your program to its security guard’s white list, you need to purchase their signature, but many people will definitely not do this, but this security guard But many people use it, because it adheres to the principle that it is better to kill a thousand people by mistake than let one go, so many softwares have serious false positives.

**Comment by za233** [comment]
That may not be possible to bypass, as this obfuscator is based on LLVM.

**Comment by LiangCha01** [comment]
But the point where 360 ​​Security Guard checks and kills should be on the surface of the program, such as the import link you mentioned. But it may also be a feature of clang. If you are interested in preventing false positives, provide your telegram and we can discuss it in detail.

**Comment by za233** [comment]
you can give me your email.
