### ISSUE TITLE
I encountered another problem

### ISSUE THREAD

**Issue by LiangCha01** [za233/Polaris-Obfuscator#4]
Problem path: llvm\lib\Target\AArch64\AArch64RubbishCode.cpp

I used vs2019 to compile llvm16.0.6. At the end of the compilation, the following error occurred in the following files:

error C2888: "void llvm::initializeAArch64RubbishCodePassPass(llvm::PassRegistry &)": cannot define symbol in namespace "anonymous-namespace"
error C2888: 'llvm::FunctionPass *llvm::createAArch64RubbishCodePassPass(void)': cannot define symbol in namespace 'anonymous-namespace'

I tried many ways and finally modified it like this
using namespace llvm;
#define DEBUG_TYPE "aarch64-obfuscation"
class AArch64RubbishCodePass : public MachineFunctionPass {
public:
  static char ID;
  AArch64RubbishCodePass() : MachineFunctionPass(ID) {}
  StringRef getPassName() const override { return "AArch64 Obfuscation"; }

  bool runOnMachineFunction(MachineFunction &MF) override;
};

char AArch64RubbishCodePass::ID = 0;

bool AArch64RubbishCodePass::runOnMachineFunction(MachineFunction &MF) {
  return false;
}

INITIALIZE_PASS(AArch64RubbishCodePass, DEBUG_TYPE, DEBUG_TYPE, false, false)

FunctionPass *llvm::createAArch64RubbishCodePassPass() {
  return new AArch64RubbishCodePass();
}

It was compiled successfully. When I compiled three programs
1. No parameters added
2. -passes=fla
3. -passes=sub
The file sizes of the three compiled programs are exactly the same. It feels like the function should not be used successfully

**Comment by za233** [comment]
Have you mark the functions that you want to obfuscate?

**Comment by LiangCha01** [comment]
I tried to mark the main like this and the generated file is still the same
__attribute((__annotate__(("indirectcall,indirectbr,aliasaccess"))))

**Comment by za233** [comment]
It seems like something different under windows platform. could you give me the .ll
file.? use command: clang xx.main -emit-llvm -mllvm -passes=fla -S -o xx.ll

**Comment by za233** [comment]
It seems like something different under windows platform. could you give me the .ll
file.? use command: clang xx.cpp -emit-llvm -mllvm -passes=fla -S -o xx.ll

**Comment by LiangCha01** [comment]
Wait a minute. I accidentally recompiled llvm because I thought it was an error. I tried to restore it to the original code.

**Comment by LiangCha01** [comment]
I uploaded two files, 1.ll and 2.ll respectively
clang++ "E:\ceshi\1.cpp" -emit-llvm -mllvm -passes=fla -S -o "E:\ceshi\1.ll"
clang++ "E:\ceshi\1.cpp" -emit-llvm -mllvm -passes=sub -S -o "E:\ceshi\2.ll"
[1.zip](https://github.com/user-attachments/files/17908863/1.zip)

**Comment by LiangCha01** [comment]
I tried to template the example2.cpp file in examples for testing and it output an error
clang++ "E:\ceshi\example2.cpp" -mllvm -passes=sub,bcf,fla  -o "E:\ceshi\example2.exe"
The error is as follows:
sub
bcf
fla
Put Block Into Switch
This block has 2 successors
This block has 2 successors
This block has 2 successors
This block has 2 successors
This block has 2 successors
This block has 1 successor
This block has 2 successors
This block has 2 successors
This block has 1 successor
This block has 2 successors
This block has 2 successors
This block has 1 successor
This block has 1 successor
This block has 1 successor
This block has 1 successor
E:\ceshi\example2.cpp:15:10: error: invalid instruction mnemonic 'backend'
        asm("backend-obfu");
            ^
<inline asm>:1:2: note: instantiated into assembly here
        backend-obfu
        ^~~~~~~~
1 error generated.

**Comment by za233** [comment]
Is your cpu architecture arm64? If not, Please switch the target architecture to X86 in Visual Studio.

**Comment by za233** [comment]
Have you decompile the obfuscated binary? The output shows that the obfuscation pass is working.

**Comment by za233** [comment]
> Wait a minute. I accidentally recompiled llvm because I thought it was an error. I tried to restore it to the original code.

Please read README file. When you mark a function, you need to specify obfuscation string, which should correspond to the command you input.
