### ISSUE TITLE
TEA encrypt example crash

### ISSUE THREAD

**Issue by hxm-cpp** [za233/Polaris-Obfuscator#5]
```
class TEA {
public:
    TEA(const std::vector<uint32_t>& key) {
        for (int i = 0; i < 4; ++i) {
            this->key[i] = key[i];
        }
    }
	__attribute((__annotate__(("flatten,boguscfg,substitution"))))
    void encrypt(uint32_t& v0, uint32_t& v1) const {							// function to be obfuscated
   
    	asm("backend-obfu");
	
        uint32_t sum = 0;
        uint32_t delta = 0x9e3779b9;
        for (int i = 0; i < 32; ++i) {
            sum += delta;
            v0 += ((v1 << 4) + key[0]) ^ (v1 + sum) ^ ((v1 >> 5) + key[1]);
            v1 += ((v0 << 4) + key[2]) ^ (v0 + sum) ^ ((v0 >> 5) + key[3]);
        }
    }
private:
    uint32_t key[4];
};

```

Assertion failed: (MCID->isVariadic() || OpNo < MCID->getNumOperands() || Op.isValidExcessOperand()) && "Trying to add an operand to a machine instr that is already done!",`

**Comment by za233** [comment]
Are you using the release version?

**Comment by za233** [comment]
I don't know how you got into this crash, but I and some others tested with the Release compilation option and didn't trigger this situation. I think this may be due to unnecessary assertions being enabled. Please modify your compilation options to disable assertions and compile again.

**Comment by hxm-cpp** [comment]
fixed with the EXCEPTIONS OFF, between any way to contact you ? i have some ideas to share.

**Comment by za233** [comment]
> fixed with the EXCEPTIONS OFF, between any way to contact you ? i have some ideas to share.

you can email me at r1mao17323@gmail.com
